# Generated by Django 4.2.3 on 2023-09-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_orders_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
