# Generated by Django 4.2.3 on 2023-09-13 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_orders_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product1'),
        ),
    ]
