# Generated by Django 4.2.3 on 2023-09-18 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_orders_address_orders_billing_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='billing_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.billing_detail'),
        ),
    ]
