# Generated by Django 4.2.3 on 2023-09-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_orders_billing_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
