# Generated by Django 4.2.3 on 2023-09-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_orders_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
